import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather, Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-header/MainHeader";

const merriweatherSans = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweatherSans.variable} ${interSans.variable} antialiased`}
      >
        <div id="page">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
